# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='author',
        ),
        migrations.AddField(
            model_name='serie',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
