# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20180119_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Serie')),
            ],
        ),
    ]
